version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 51553:1972
      - 52553:52773
      - 53773
    volumes:
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
